# Site settings
title: Niceoutput
email: mario.pedro@niceoutput.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end developer for almost 12 years, experienced in agency and large environments. 
  Now at Uniplaces to make the web better.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.niceoutput.com" # the base hostname & protocol for your site

twitter_username: niceoutput
github_username:  niceoutput

permalink: /:categories/:title

comments: true

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown